### ISSUE TITLE
Post Example

### ISSUE THREAD

**Issue by ghost** [brainwipe/NJsonApiCore#17]
Hi,

Do you have an example of the body to post to the articles endpoint?

Thanks,
Prince.

**Comment by brainwipe** [comment]
Hi Prince, good question. I'll add that into readme and will close this when completed.

As per the [{json:api} specification](http://jsonapi.org/format/#crud), although I appreciate the example there is `photos/`, not `articles/`

```
POST /articles HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "To TDD or Not"
    }
  }
}
```

**Comment by ghost** [comment]
Hi,

Thanks for the quick reply. 
I've tried that, but it seems that the de-serialisation doesn't work properly.

After "var newArticle = article.ToObject();", all the properties are set to the default values.

Thanks,
Prince.

**Comment by brainwipe** [comment]
No problem. 
Are you using Core or .NET 4.6.2? Are you running the examples provided or do you have your own code?

**Comment by ghost** [comment]
I am running your MVCCore.HelloWorld solution.

**Comment by brainwipe** [comment]
@kprilux thanks for persevering, I've just run up the code and found that the controller registration validation is failing! I'll need to fix that before I can reproduce your problem. :)

**Comment by ghost** [comment]
Yes, I've noticed that. I commented lines 46 to 50 in ConfigurationBuilder.cs.
Also I had to add the following line in Startup.cs:
options.InputFormatters.OfType<JsonInputFormatter>().First().SupportedMediaTypes.Add(new MediaTypeHeaderValue("application/vnd.api+json"));

**Comment by brainwipe** [comment]
Bocked by #18

**Comment by brainwipe** [comment]
#18 is now fixed so the `ConfigurationBuilder` should be working as designed. I'll get onto the POST problem you've outlined later today.

I'm interested by the addition of `InputFormatters` as I've not needed that while running my tests through Postman. What error were you getting without it?

**Comment by ghost** [comment]
I get a 415 error (Unsupported Media Type)

**Comment by ghost** [comment]
So I got it working by creating an IResourceFilter
According to https://docs.asp.net/en/latest/mvc/controllers/filters.html#resource-filters, you can't read the 
HTTP body stream after the model binding (ActionFilterAttribute is executed after the model binding)

I'll test it a bit and push it to a different branch.

**Comment by ghost** [comment]
It looks like I don't have the permission to push to a new branch.

**Comment by ghost** [comment]
I've created a pull request :)

**Comment by brainwipe** [comment]
@kprilux Pull request #19 merged to master, will go with next release.
