### ISSUE TITLE
Possible spec deviation: include & relationship names

### ISSUE THREAD

**Issue by burgessl** [brainwipe/NJsonApiCore#20]
First of all, great work on getting this library up and running for .NET Core. I have just started using JSON API in a .NET Core project and finding that this existed was a pleasant surprise.

I have noticed one thing I think isn't quite in-line with the JSON API spec - the names used when including related data. I read the spec as the names used in the include parameter where the relationship names whereas NJSONApiCore seems to require the 'relationship type name' to be used.

The bit from the spec is:

> The value of the include parameter MUST be a comma-separated (U+002C COMMA, “,”) list of relationship paths. A relationship path is a dot-separated (U+002E FULL-STOP, “.”) list of relationship names.

An example (the standard article/comment/author one):

```
{
  "links": {
    "self": "http://example.com/articles",
    "next": "http://example.com/articles?page[offset]=2",
    "last": "http://example.com/articles?page[offset]=10"
  },
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    },
    "links": {
      "self": "http://example.com/articles/1"
    }
  }]
}
```

In this the relationship names are 'comments' and 'author' on the article resource. The type are 'comments' for a comment and 'people' for an author.

If I wanted to fetch an article's author I would expect the include to be `include=author` where author is the relationship I want to include.

Currently the default behaviour in NJsonAPICore is to require that to be: `include=people` where I need to use the type of the relationship, not the specific relationship.

I'll try and find some time to put together a PR for this but I wanted to open a discussion about it first - I can see this being a breaking change for people already using the library.

**Comment by brainwipe** [comment]
Thank you and great spot! Yes, I think you're right. That's a deviation. The spec makes more sense as when you're dealing with resource `Article` then you don't really know about `People`, you only really understand `Author`.

Shouldn't be too hard to fix, I'll look forward to the PR.

Thanks for contributing!
