### ISSUE TITLE
Returning an array from a controller results in a MissingMappingsException

### ISSUE THREAD

**Issue by burgessl** [brainwipe/NJsonApiCore#21]
If you return an array from a controller (instead of say a List<T>) the JsonApiActionFilter will throw a MissingMappingsException. This occurs as the element type of the array is not reflected (the code only handles classes that are assignable to IEnumerable<T>).

A pretty minor thing but easy to fix :)

**Comment by burgessl** [comment]
Nah no urgency at all. You can just make things a proper collection type as a workaround (which is probably a better choice over an array anyway in most cases). 

Just felt like a good choice for a first pull request as it was nice and easy :)

**Comment by brainwipe** [comment]
I prefer Arrays to `IEnumerable` as you are never entirely sure when the `IEnumerable` will be enumerated.
