### ISSUE TITLE
.NET Core 

### ISSUE THREAD

**Issue by miclip** [brainwipe/NJsonApiCore#5]
Any plans to update this for 1.0?

**Comment by brainwipe** [comment]
tldr; yes!

My employer's long term tech strategy is to go .NET Core JSONApi backend with a ReactJS front end, so I will be getting back onto moving it to 1.0 this summer.

**Comment by miclip** [comment]
Awesome, I might fork it and tinker myself. Thanks

**Comment by miclip** [comment]
Updated NJsonApiCore to support ASP.NET Core 1.0 and created a Web.MVCCore and HelloWorld. 

https://github.com/miclip/NJsonApiCore

**Comment by brainwipe** [comment]
Going to reopen as a reminder to pull your repo down and check the commits.

**Comment by miclip** [comment]
There was only a couple of changes: the JsonOutputFormatter constructors now require the SerializationSettings and char ArrayPool. 

The Startup.cs changes for UseIISPlatform and UseStaticFiles.

**Comment by brainwipe** [comment]
Implemented and released.

FYI. I needed to put back in the NJsonApiCore.project.json and the CSPROJ as these files are needed by the MVC 5 (.NET 4.5.2) platforms. It's not a good solution, but it is the correct solution as per Microsoft's instructions until they deprecate project.json entirely.
